SELECT U.NOME, PTA.NOTA, PTA.COMENTARIO FROM USUARIO U 
INNER JOIN TURISTA T ON (T.IDUSUARIO = U.IDUSUARIO) 
INNER JOIN PONTOTURISTICOAVALIACAO PTA ON (PTA.IDTURISTA = T.IDTURISTA) 
INNER JOIN PONTOTURISTICO PT ON (PT.IDPONTOTURISTICO = PTA.IDPONTOTURISTICO)
WHERE PT.nome_pontoturistico ILIKE 'Praia Secreta';
