SELECT USUARIO.NOME, TURISTA.SEXO, PONTOTURISTICO.NOME_PONTOTURISTICO, PONTOTURISTICO.TIPO_PONTOTURISTICO,
PONTOTURISTICO.PUBLICO_ALVO, PONTOTURISTICO.TIPO_AMBIENTE, PONTOTURISTICOAVALIACAO.DT_VISITA 
FROM USUARIO 
INNER JOIN TURISTA ON (USUARIO.IDUSUARIO = TURISTA.IDUSUARIO) 
INNER JOIN PONTOTURISTICOAVALIACAO ON (PONTOTURISTICOAVALIACAO.IDTURISTA = TURISTA.IDTURISTA) 
INNER JOIN PONTOTURISTICO ON (PONTOTURISTICO.IDPONTOTURISTICO = PONTOTURISTICOAVALIACAO.IDPONTOTURISTICO) 
ORDER BY DT_VISITA DESC;
