SELECT O.NUMERO_LINHA, O.NOME_LINHA FROM ONIBUS O INNER JOIN 
ONIBUSPONTOTURISTICO OPT ON (OPT.IDONIBUS = O.IDONIBUS) 
INNER JOIN PONTOTURISTICO PT ON (PT.IDPONTOTURISTICO = OPT.IDPONTOTURISTICO)
WHERE PT.NOME_PONTOTURISTICO ILIKE 'Convento da Penha';
