SELECT U.NOME, PT.NOME_PONTOTURISTICO, AGE(CURRENT_DATE, PTA.DT_VISITA) 
FROM USUARIO U 
INNER JOIN TURISTA T ON (U.IDUSUARIO = T.IDUSUARIO) 
INNER JOIN PontoTuristicoAvaliacao PTA ON (PTA.IDTURISTA = T.IDTURISTA) 
INNER JOIN PONTOTURISTICO PT ON (PT.IDPONTOTURISTICO = PTA.IDPONTOTURISTICO) ORDER BY AGE;
