SELECT PONTOTURISTICO.NOME_PONTOTURISTICO, (SUM(PONTOTURISTICOAVALIACAO.NOTA)/ COUNT(PONTOTURISTICOAVALIACAO.NOTA)) AS MEDIA_NOTA 
FROM PONTOTURISTICO INNER JOIN 
PONTOTURISTICOAVALIACAO ON (PONTOTURISTICO.IDPONTOTURISTICO = PONTOTURISTICOAVALIACAO.IDPONTOTURISTICO) 
GROUP BY PONTOTURISTICO.NOME_PONTOTURISTICO ORDER BY MEDIA_NOTA ASC;
