CREATE TABLE USUARIO (
idusuario SERIAL PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
tipo_usuario VARCHAR(30) NOT NULL,
dt_nascimento DATE,
sexo VARCHAR(10),
email VARCHAR(50) UNIQUE,
senha VARCHAR(30)
);

CREATE TABLE PONTOTURISTICO (
idpontoturistico SERIAL PRIMARY KEY,
id_usuario INT,
cnpj VARCHAR(15) UNIQUE,
tipo_pontoturistico VARCHAR(30),
descricao VARCHAR(1000),
publico_alvo VARCHAR(30),
tipo_ambiente VARCHAR(30),
logradouro VARCHAR(100),
numero INT,
bairro VARCHAR(50),
cep VARCHAR(15),
municipio VARCHAR(50)
);

CREATE TABLE EVENTO (
idevento SERIAL PRIMARY KEY,
id_pontoturistico INT NOT NULL,
descricao_evento VARCHAR(1000),
dt_evento DATE,
hr_evento TIME,
link_evento VARCHAR(300)
);


CREATE TABLE ONIBUS (
idonibus SERIAL PRIMARY KEY,
numero_linha INT,
nome_linha VARCHAR(100),
sistema_transporte VARCHAR(30)
);

CREATE TABLE PONTOTURISTICOONIBUS (
idponto_turistico SERIAL PRIMARY KEY,
id_pontoturistico INT NOT NULL,
id_onibus INT NOT NULL
);

CREATE TABLE PONTOTURISTICOAVALIACAO (
idpontoturisticoavaliacao SERIAL PRIMARY KEY,
id_usuario INT NOT NULL,
id_pontoturistico INT NOT NULL,
nota NUMERIC,
comentario VARCHAR(1000),
dt_avaliacao DATE,
hr_avaliacao TIME
);

CREATE TABLE HISTORICOVISITA (
idhistoricovisita SERIAL PRIMARY KEY,
id_usuario INT NOT NULL,
id_pontoturistico INT NOT NULL,
dt_visita DATE,
hr_visita TIME
);

ALTER TABLE PONTOTURISTICO ADD CONSTRAINT PONTOTURISTICO_USUARIO_FK
FOREIGN KEY (id_usuario) REFERENCES USUARIO(idusuario) 
MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PONTOTURISTICOONIBUS ADD CONSTRAINT PONTOTURISTICOONIBUS_ONIBUS_FK
FOREIGN KEY (id_onibus) REFERENCES ONIBUS(idonibus) 
MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PONTOTURISTICOONIBUS ADD CONSTRAINT PONTOTURISTICOONIBUS_PONTOTURISTICO_FK
FOREIGN KEY (id_pontoturistico) REFERENCES PONTOTURISTICO(idpontoturistico) 
MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PONTOTURISTICOAVALIACAO ADD CONSTRAINT PONTOTURISTICOAVALIACAO_USUARIO_FK
FOREIGN KEY (id_usuario) REFERENCES USUARIO(idusuario);

ALTER TABLE PONTOTURISTICOAVALIACAO ADD CONSTRAINT PONTOTURISTICOAVALIACAO_PONTOTURISTICO_FK
FOREIGN KEY (id_pontoturistico) REFERENCES PONTOTURISTICO(idpontoturistico);

ALTER TABLE HISTORICOVISITA ADD CONSTRAINT HISTORICOVISITA_USUARIO_FK
FOREIGN KEY (id_usuario) REFERENCES USUARIO(idusuario);

ALTER TABLE HISTORICOVISITA ADD CONSTRAINT HISTORICOVISITA_PONTOTURISTICO_FK
FOREIGN KEY (id_pontoturistico) REFERENCES PONTOTURISTICO(idpontoturistico);