CREATE TYPE TIPO_SEXO AS ENUM('M','F');
    
   CREATE TABLE PESSOA(
  	IDPESSOA SERIAL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
TIPO_USUARIO VARCHAR(50) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SEXO TIPO_SEXO NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
SENHA VARCHAR(30) 
   );
   CREATE TABLE EMPREENDIMENTO(
    IDEMPREENDIMENTO SERIAL PRIMARY KEY,
    TIPO_USUARIO VARCHAR(50),
    TIPO_EMPREENDIMENTO VARCHAR(30),
    NOME VARCHAR(100) NOT NULL,
    PUBLICO_ALVO VARCHAR(50),
    TIPO_AMBIENTE VARCHAR(50) NOT NULL,
    CNPJ VARCHAR(15),
    DESCRICAO VARCHAR(250),
    EMAIL VARCHAR(50) UNIQUE,
    SENHA VARCHAR(30),
    TIPO_LOGRADOURO VARCHAR(30),
    LOGRADOURO VARCHAR(100),
    NUMERO INT,
    CEP VARCHAR(15)
   );
   CREATE TABLE HISTORICOVISITA(
    IDHISTORICOVISITA SERIAL PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    ID_EMPREENDIMENTO INT NOT NULL,
    DATA_VISITA DATE,
    HORA TIME
   );
   CREATE TABLE EVENTO(
    IDEVENTO SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(250) NOT NULL,
    DATA_EVENTO DATE,
    HORA TIME,
    LINK VARCHAR(250)
   );
   CREATE TABLE EMPREENDIMENTO_EVENTO(
    IDEMPREENDIMENTO_EVENTO SERIAL PRIMARY KEY,
    ID_EMPREENDIMENTO INT NOT NULL,
    ID_EVENTO INT NOT NULL
   );

   CREATE TABLE ONIBUS(
    IDONIBUS SERIAL PRIMARY KEY,
    LINHA VARCHAR(15) NOT NULL,
    DESCRICAO VARCHAR(250),
    SISTEMA_TRANSPORTE VARCHAR(50)
   );

   CREATE TABLE EMPREENDIMENTO_ONIBUS(
    IDEMPREENDIMENTO_EVENTO SERIAL PRIMARY KEY,
    ID_EMPREENDIMENTO INT NOT NULL,
    ID_ONIBUS INT NOT NULL
   );

   CREATE TABLE AVALIACAOLOCAL(
    IDAVALIACAOLOCAL SERIAL PRIMARY KEY,
    ID_PESSOA INT NOT NULL,
    ID_EMPREENDIMENTO INT NOT NULL,
    COMENTARIO VARCHAR(250),
    NOTA INT,
    DATA_AVALIACAO DATE,
    HORA TIME
   );
   
   ALTER TABLE HISTORICOVISITA ADD CONSTRAINT PESSOA_HISTORICOVISITA_FK
   FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(IDPESSOA) MATCH FULL ON UPDATE CASCADE;

   ALTER TABLE HISTORICOVISITA ADD CONSTRAINT EMPREENDIMENTO_HISTORICOVISITA_FK
   FOREIGN KEY (ID_EMPREENDIMENTO) REFERENCES EMPREENDIMENTO(IDEMPREENDIMENTO) ON UPDATE CASCADE;

   ALTER TABLE EMPREENDIMENTO_EVENTO ADD CONSTRAINT EMPREENDIMENTO_EMPREENDIMENTO_EVENTO_FK
   FOREIGN KEY (ID_EMPREENDIMENTO) REFERENCES EMPREENDIMENTO(IDEMPREENDIMENTO)
   MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

   ALTER TABLE EMPREENDIMENTO_EVENTO ADD CONSTRAINT EVENTO_EMPREENDIMENTO_EVENTO_FK
   FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(IDEVENTO)
   MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

   ALTER TABLE EMPREENDIMENTO_ONIBUS ADD CONSTRAINT EMPREENDIMENTO_EMPREENDIMENTO_ONIBUS_FK
   FOREIGN KEY (ID_EMPREENDIMENTO) REFERENCES EMPREENDIMENTO(IDEMPREENDIMENTO)
   MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;

   ALTER TABLE EMPREENDIMENTO_ONIBUS ADD CONSTRAINT EVENTO_EMPREENDIMENTO_ONIBUS_FK
   FOREIGN KEY (ID_ONIBUS) REFERENCES ONIBUS(IDONIBUS)
   MATCH FULL ON UPDATE CASCADE ON DELETE CASCADE;
   
   ALTER TABLE AVALIACAOLOCAL ADD CONSTRAINT AVALIACAOLOCAL_EMPREENDIMENTO_FK
   FOREIGN KEY (ID_EMPREENDIMENTO) REFERENCES EMPREENDIMENTO(IDEMPREENDIMENTO)
   MATCH FULL ON UPDATE CASCADE;

   ALTER TABLE AVALIACAOLOCAL ADD CONSTRAINT AVALIACAOLOCAL_PESSOA_FK
   FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
   MATCH FULL ON UPDATE CASCADE;